#!/usr/bin/env python3
# STRATA — STAGE 0 BOOTSTRAP COMPILER
# Compiles .sta source files to C, then invokes clang/gcc
# This is the ONLY Python in the Strata toolchain.
from __future__ import annotations
import sys, os, subprocess
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from compiler.lexer import Lexer, Token, TT, LexError, tokenise_file
from compiler.parser import (
    Parser, CompilationUnit, ParseError, parse_file,
    DatabaseDecl, ProtocolDecl, ModelDecl, ReportDecl,
    FunctionDecl, ImportDecl, FieldDecl, Param,
    VarDecl, ReturnStmt, IfStmt, PrintStmt, ExprStmt,
    AssertStmt, RenderStmt, VerifyBlock,
    BinaryExpr, UnaryExpr, CallExpr, BorrowExpr, CastExpr,
    PredictExpr, QueryExpr, ListLiteral, MemberAccess,
    IntLiteral, FloatLiteral, StrLiteral, BoolLiteral, Identifier,
    PrimitiveType, ListType, TensorType,
)

C_PREAMBLE = r"""
/* Generated by Strata Stage 0 Bootstrap Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include <ctype.h>
typedef int64_t   strata_int;
typedef double    strata_float;
typedef char*     strata_str;
typedef int64_t   strata_bool;
#define STRATA_TRUE  1
#define STRATA_FALSE 0
static strata_str strata_concat(strata_str a, strata_str b) {
    size_t la=strlen(a),lb=strlen(b);
    strata_str r=(strata_str)malloc(la+lb+1);
    memcpy(r,a,la); memcpy(r+la,b,lb+1); return r;
}
static strata_str strata_int_to_str(strata_int v) {
    strata_str b=(strata_str)malloc(32);
    snprintf(b,32,"%lld",(long long)v); return b;
}
static strata_str strata_float_to_str(strata_float v) {
    strata_str b=(strata_str)malloc(64);
    snprintf(b,64,"%.6f",v); return b;
}
"""

class CodeGen:
    def __init__(self,ast,source_path):
        self.ast=ast; self.source_path=source_path
        self.out=[]; self.indent=0
        self.schemas={}; self.func_returns={}; self.var_types={}

    def emit(self,line=""): self.out.append("    "*self.indent+line)
    def emit_raw(self,line): self.out.append(line)

    def generate(self):
        self.emit_raw(C_PREAMBLE)
        for d in self.ast.declarations: self._forward_declare(d)
        for d in self.ast.declarations: self._gen_decl(d)
        for f in self.ast.functions: self._forward_fn(f)
        for f in self.ast.functions: self._gen_function(f)
        return "\n".join(self.out)

    def _forward_declare(self,d):
        if isinstance(d,(DatabaseDecl,ProtocolDecl)):
            self.emit_raw(f"typedef struct {d.name} {d.name};")

    def _forward_fn(self,fn):
        rt=self._c_type(fn.return_type) if fn.return_type else "void"
        if fn.kind=="def": rt="void"
        params=", ".join(self._c_param(p) for p in fn.params) if fn.params else "void"
        self.emit_raw(f"{rt} {fn.name}({params});")

    def _gen_decl(self,d):
        if isinstance(d,DatabaseDecl):
            self._gen_struct(d.name,d.fields)
            self.schemas[d.name]=[f.name for f in d.fields]
        elif isinstance(d,ProtocolDecl): self._gen_struct(d.name,d.fields)
        elif isinstance(d,ModelDecl): self._gen_model(d)
        elif isinstance(d,ReportDecl): self._gen_report(d)

    def _gen_struct(self,name,fields):
        self.emit_raw(f"\nstruct {name} {{")
        for f in fields: self.emit_raw(f"    {self._c_type(f.field_type)} {f.name};")
        self.emit_raw(f"}};")

    def _gen_model(self,d):
        self.emit_raw(f"\ntypedef struct {{ int rows_in,cols_in,rows_out,cols_out; double* weights; }} {d.name};")
        self.emit_raw(f"static {d.name} {d.name}_instance = {{{d.input_type.rows},{d.input_type.cols},{d.output_type.rows},{d.output_type.cols},NULL}};")

    def _gen_report(self,d):
        self.emit_raw(f"\nvoid {d.name}_generate(FILE* _out) {{")
        self.emit_raw(f'    fprintf(_out,"# {d.title}\\n");')
        self.emit_raw(f"}}")

    def _gen_function(self,fn):
        rt=self._c_type(fn.return_type) if fn.return_type else "void"
        if fn.kind=="def": rt="void"
        params=", ".join(self._c_param(p) for p in fn.params) if fn.params else "void"
        self.func_returns[fn.name]=rt; self.var_types={}
        self.emit_raw(f"\n{rt} {fn.name}({params}) {{")
        self.indent=1
        for s in fn.body: self._gen_stmt(s)
        self.indent=0; self.emit_raw("}")

    def _gen_stmt(self,s):
        if isinstance(s,VarDecl): self._gen_var_decl(s)
        elif isinstance(s,ReturnStmt):
            self.emit(f"return {self._gen_expr(s.value)};") if s.value else self.emit("return;")
        elif isinstance(s,IfStmt): self._gen_if(s)
        elif isinstance(s,PrintStmt):
            self.emit(f'printf("%s\\n",(strata_str)({self._gen_expr(s.value)}));')
        elif isinstance(s,AssertStmt):
            self.emit(f'if(!({self._gen_expr(s.condition)})){{fprintf(stderr,"[STRATA ASSERT FAILED] line {s.line}\\n");exit(1);}}')
        elif isinstance(s,RenderStmt):
            self.emit(f'{{FILE* _rf=fopen("{s.path}","w");{s.report}_generate(_rf);fclose(_rf);}}')
        elif isinstance(s,VerifyBlock):
            self.emit(f'/* verify: {s.label} */')
            for a in s.assertions: self._gen_stmt(a)
        elif isinstance(s,ExprStmt): self.emit(f"{self._gen_expr(s.expr)};")

    def _gen_var_decl(self,s):
        ct=self._c_type(s.var_type); name=s.name
        if isinstance(s.value,QueryExpr):
            src=s.value.source
            if src in self.schemas: self._validate_query_cols(s.value.condition,src,s.line)
            self.emit(f"{ct} {name}=NULL;/* query:{src} */")
        else:
            self.emit(f"{ct} {name}={self._gen_expr(s.value)};")
        self.var_types[name]=ct

    def _validate_query_cols(self,cond,schema,line):
        cols=self.schemas.get(schema,[])
        if isinstance(cond,BinaryExpr):
            if isinstance(cond.left,Identifier) and cond.left.name not in cols:
                print(f"[E004] Schema Violation line {line}: '{cond.left.name}' not in '{schema}'. Valid: {cols}",file=sys.stderr)
                sys.exit(1)
            self._validate_query_cols(cond.left,schema,line)
            self._validate_query_cols(cond.right,schema,line)

    def _gen_if(self,s):
        self.emit(f"if ({self._gen_expr(s.condition)}) {{")
        self.indent+=1
        for st in s.then_block: self._gen_stmt(st)
        self.indent-=1
        if s.else_block:
            self.emit("} else {"); self.indent+=1
            for st in s.else_block: self._gen_stmt(st)
            self.indent-=1
        self.emit("}")

    def _gen_expr(self,e):
        if isinstance(e,IntLiteral): return str(e.value)
        if isinstance(e,FloatLiteral): return str(e.value)
        if isinstance(e,StrLiteral):
            esc=e.value.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n')
            return f'"{esc}"'
        if isinstance(e,BoolLiteral): return "1" if e.value else "0"
        if isinstance(e,Identifier): return e.name
        if isinstance(e,BinaryExpr):
            l=self._gen_expr(e.left); r=self._gen_expr(e.right)
            if e.op=="+": return f"strata_concat({l},{r})"
            return f"({l} {e.op} {r})"
        if isinstance(e,UnaryExpr): return f"({e.op}{self._gen_expr(e.operand)})"
        if isinstance(e,CallExpr): return self._gen_call(e)
        if isinstance(e,BorrowExpr): return f"(&{self._gen_expr(e.target)})"
        if isinstance(e,CastExpr): return f"(({e.target_type}*)({self._gen_expr(e.source)}))"
        if isinstance(e,PredictExpr): return f"strata_predict(&{e.model}_instance,{self._gen_expr(e.arg)})"
        if isinstance(e,ListLiteral): return "NULL"
        if isinstance(e,MemberAccess): return f"{self._gen_expr(e.obj)}.{e.member}"
        if isinstance(e,QueryExpr): return f"NULL/*query {e.source}*/"
        return "0"

    def _gen_call(self,e):
        if e.callee=="str": return f"strata_int_to_str({self._gen_expr(e.args[0])})"
        if e.callee=="int": return f"((strata_int)({self._gen_expr(e.args[0])}))"
        if e.callee=="float": return f"((strata_float)({self._gen_expr(e.args[0])}))"
        args=", ".join(self._gen_expr(a) for a in e.args)
        return f"{e.callee}({args})"

    def _c_type(self,t):
        if t is None: return "void"
        if isinstance(t,PrimitiveType):
            return {"int":"strata_int","float":"strata_float","str":"strata_str","void":"void","bool":"strata_bool"}.get(t.name,t.name)
        if isinstance(t,ListType): return f"{self._c_type(t.element_type)}*"
        if isinstance(t,TensorType): return "double*"
        return "void*"

    def _c_param(self,p):
        return f"{self._c_type(p.param_type)}{'*' if p.borrow else ''} {p.name}"

def compile_sta(source_path,output_path,target="native",verbose=False):
    print(f"[Strata Stage 0] Compiling '{source_path}'...")
    try: ast=parse_file(source_path)
    except (LexError,ParseError) as e: print(str(e),file=sys.stderr); sys.exit(1)
    if verbose:
        print(f"  AST: {len(ast.imports)} imports, {len(ast.declarations)} decls, {len(ast.functions)} functions")
    gen=CodeGen(ast,source_path); c_source=gen.generate()
    base=os.path.splitext(source_path)[0]; c_path=base+".c"
    with open(c_path,"w") as f: f.write(c_source)
    print(f"  C source: {c_path}")
    cc=next((c for c in ("clang","gcc","cc") if subprocess.run(["which",c],capture_output=True).returncode==0),None)
    if not cc: print("[STRATA ERROR] No C compiler found.",file=sys.stderr); sys.exit(1)
    if target=="wasm":
        flags=[cc,"-O2","--target=wasm32","--no-standard-libraries","-Wl,--export-all","-Wl,--no-entry","-o",output_path,c_path]
    else:
        flags=[cc,"-O2","-o",output_path,c_path,"-lm"]
    if verbose: print(f"  Invoking: {' '.join(flags)}")
    r=subprocess.run(flags,capture_output=True,text=True)
    if r.returncode!=0: print(f"[STRATA C ERROR]\n{r.stderr}",file=sys.stderr); sys.exit(1)
    print(f"  Binary: {output_path}")
    print(f"[Strata Stage 0] Done. ✓")

def _find_cc():
    for c in ("clang","gcc","cc"):
        if subprocess.run(["which",c],capture_output=True).returncode==0: return c
    print("[STRATA ERROR] No C compiler.",file=sys.stderr); sys.exit(1)

def main():
    import argparse
    ap=argparse.ArgumentParser(description="Strata Stage 0 Bootstrap Compiler")
    ap.add_argument("file"); ap.add_argument("-o","--output",default=None)
    ap.add_argument("--target",choices=["native","wasm","c"],default="native")
    ap.add_argument("--ast",action="store_true")
    ap.add_argument("--emit-c",action="store_true")
    ap.add_argument("-v","--verbose",action="store_true")
    args=ap.parse_args()
    if args.ast:
        import json; ast=parse_file(args.file); print(json.dumps(ast.to_dict(),indent=2)); return
    base=os.path.splitext(args.file)[0]; out=args.output or base
    if args.emit_c:
        try: ast=parse_file(args.file)
        except (LexError,ParseError) as e: print(str(e),file=sys.stderr); sys.exit(1)
        print(CodeGen(ast,args.file).generate()); return
    compile_sta(args.file,out,target=args.target,verbose=args.verbose)

if __name__=="__main__": main()
