
/* Generated by Strata Stage 0 Bootstrap Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include <math.h>
#include <ctype.h>

typedef int64_t   strata_int;
typedef double    strata_float;
typedef char*     strata_str;
typedef int64_t   strata_bool;

#define STRATA_TRUE  1
#define STRATA_FALSE 0

int __strata_argc = 0;
char** __strata_argv = NULL;

static strata_str strata_concat(strata_str a, strata_str b) {
    size_t la=strlen(a),lb=strlen(b);
    strata_str r=(strata_str)malloc(la+lb+1);
    memcpy(r,a,la); memcpy(r+la,b,lb+1); return r;
}
static strata_str strata_int_to_str(strata_int v) {
    strata_str b=(strata_str)malloc(32);
    snprintf(b,32,"%lld",(long long)v); return b;
}
static strata_str strata_float_to_str(strata_float v) {
    /* %.17g round-trips, then trailing zeros are trimmed so 91.4 prints as
       "91.4" rather than "91.400000". A fixed 6-decimal format made every
       rendered float look padded. */
    strata_str b=(strata_str)malloc(64);
    /* Shortest representation that reads back as the same double: %.17g always
       round-trips but shows binary noise (91.400000000000006), so try shorter
       precisions first. */
    int p;
    for (p = 15; p <= 17; p++) {
        snprintf(b,64,"%.*g",p,v);
        if (strtod(b,NULL) == v) break;
    }
    if (!strchr(b,'e') && !strchr(b,'E')) {
        char* dot=strchr(b,'.');
        if (dot) {
            char* end=b+strlen(b)-1;
            while (end>dot && *end=='0') { *end='\0'; end--; }
            if (end==dot) { *(end+1)='0'; *(end+2)='\0'; }
        } else {
            /* A float is shown as a float: 3.0, not 3. */
            strcat(b,".0");
        }
    }
    return b;
}
static strata_int str_len(strata_str s) { return (strata_int)strlen(s); }
static strata_str str_concat(strata_str a, strata_str b) { return strata_concat(a,b); }
static strata_str int_to_str(strata_int v) { return strata_int_to_str(v); }
static strata_str float_to_str(strata_float v) { return strata_float_to_str(v); }
static strata_int str_eq(strata_str a, strata_str b) { return strcmp(a,b)==0?1:0; }
static strata_int str_to_int(strata_str s) { return (strata_int)atoll(s); }
static strata_str str_slice(strata_str s, strata_int start, strata_int end) {
    strata_int len=(strata_int)strlen(s);
    if(start<0)start=0; if(end>len)end=len;
    strata_int sz=end-start; if(sz<=0)return "";
    strata_str r=(strata_str)malloc(sz+1);
    memcpy(r,s+start,sz); r[sz]='\0'; return r;
}
static strata_int str_index_of(strata_str h, strata_str n) {
    char* p=strstr(h,n); return p?(strata_int)(p-h):-1;
}
static strata_int str_starts_with(strata_str s, strata_str p) {
    return strncmp(s,p,strlen(p))==0?1:0;
}
static strata_str file_read(strata_str path) {
    FILE* f=fopen(path,"r"); if(!f)return "";
    fseek(f,0,SEEK_END); long sz=ftell(f); rewind(f);
    char* b=(char*)malloc(sz+1); fread(b,1,sz,f); b[sz]='\0'; fclose(f); return b;
}
static strata_int file_write(strata_str path, strata_str content) {
    FILE* f=fopen(path,"w"); if(!f)return 0;
    fputs(content,f); fclose(f); return 1;
}
static strata_int file_exists(strata_str path) {
    FILE* f=fopen(path,"r"); if(f){fclose(f);return 1;} return 0;
}

/* StringBuilder */
typedef struct { char* buf; int64_t len; int64_t cap; } SB;
static SB sb_new_f(void) { SB s; s.cap=4096;s.len=0;s.buf=(char*)malloc(4096);s.buf[0]='\0';return s; }
static void sb_append_f(SB* s, const char* t) {
    size_t tl=strlen(t);
    while(s->len+(int64_t)tl+1>s->cap){s->cap*=2;s->buf=(char*)realloc(s->buf,s->cap);}
    memcpy(s->buf+s->len,t,tl+1); s->len+=(int64_t)tl;
}
static void sb_append_line_f(SB* s, const char* t) {
    sb_append_f(s,t); sb_append_f(s,"\n");
}

/* ── In-memory table runtime ──────────────────────────────────────────────
   Each `database` block gets a fixed-capacity table of row pointers. A query
   allocates a NULL-terminated array of matching rows; `len` counts it. This is
   deliberately the simplest thing that makes the cross-tier contract
   observable end to end — there is no persistence, no index and no
   transaction. */
#define STRATA_TABLE_CAP 4096

/* ── Lists ────────────────────────────────────────────────────────────────
   A list value is a pointer to its first element, with its element COUNT in
   the machine word immediately before it.

   The obvious alternative, NULL-termination, cannot work: 0 is a valid int
   and "" a valid str, so there is no element value free to act as a
   terminator. It was what strata_len assumed, which is why len([1,2,3])
   returned whatever happened to follow the array on the stack.

   strata_int is 8 bytes, so the data pointer stays 8-byte aligned and a
   double or a pointer can sit there. */
static void* strata_list_new(strata_int count, size_t elem_size) {
    strata_int* base = (strata_int*)calloc(1, sizeof(strata_int)
                                              + (size_t)count * elem_size);
    if (!base) return NULL;
    base[0] = count;
    return (void*)(base + 1);
}

/* A query allocates for every row in the table and then reports how many
   actually matched. */
static void strata_list_set_len(void* list, strata_int count) {
    if (list) ((strata_int*)list)[-1] = count;
}

static strata_int strata_len(void* list) {
    if (!list) return 0;
    return ((strata_int*)list)[-1];
}

/* ── Aggregates ───────────────────────────────────────────────────────────
   sum, avg, min and max over a list of numbers, or over one column projected
   out of a list of rows. The column case walks an array of row pointers and
   reads a field at a known byte offset, which is what lets a single runtime
   function serve every schema.

   Empty input: sum is 0, and avg, min and max are 0 too rather than an error
   or a NaN. A report over a filter that matched nothing should render zeroes,
   not fail. */
#define STRATA_AGG_SUM 0
#define STRATA_AGG_AVG 1
#define STRATA_AGG_MIN 2
#define STRATA_AGG_MAX 3

/* kind: 0 sum, 1 avg, 2 min, 3 max.  elem: 'i' int, 'f' float.
   offset < 0 means the list holds the numbers directly; otherwise it holds
   row pointers and the number is at that byte offset inside each row. */
static double strata_agg(void* list, int kind, char elem, long offset) {
    strata_int n = strata_len(list);
    if (n <= 0 || !list) return 0.0;
    double acc = 0.0, best = 0.0;
    for (strata_int i = 0; i < n; i++) {
        const void* cell;
        if (offset < 0) {
            cell = (const char*)list + (size_t)i * (elem == 'f' ? sizeof(double)
                                                                : sizeof(strata_int));
        } else {
            void* row = ((void**)list)[i];
            if (!row) continue;
            cell = (const char*)row + offset;
        }
        double v = (elem == 'f') ? *(const double*)cell
                                 : (double)*(const strata_int*)cell;
        acc += v;
        if (i == 0) { best = v; }
        if (kind == STRATA_AGG_MIN) { if (v < best) best = v; }
        if (kind == STRATA_AGG_MAX) { if (v > best) best = v; }
    }
    if (kind == STRATA_AGG_SUM) return acc;
    if (kind == STRATA_AGG_AVG) return acc / (double)n;
    return best;
}

/* ── Inference runtime ────────────────────────────────────────────────────
   A model is one dense layer: output = input × W + b, with W laid out
   row-major as cols_in × cols_out followed by cols_out bias terms. That is
   the whole of it — no hidden layers, no activations beyond the identity, no
   training, no accelerator. It is enough for a linear model to run and for
   the E006 shape contract to mean something end to end, and nothing more is
   claimed. */
#define STRATA_MAX_LAYERS 16

/* A model is a stack of dense layers. `dims` holds nlayers+1 widths — the
   input width, then each layer's output width — and `acts` the activation
   applied after each layer: 'r' relu, 's' sigmoid, 'n' none. A model with no
   hidden layers is one layer, so there is a single forward pass here rather
   than a special case. */
typedef struct {
    int rows_in, cols_in, rows_out, cols_out;
    double* weights;
    int nlayers;
    int dims[STRATA_MAX_LAYERS + 1];
    char acts[STRATA_MAX_LAYERS];
} StrataModel;

static double* strata_tensor(strata_int n) {
    double* t = (double*)calloc((size_t)n, sizeof(double));
    return t;
}
static void strata_tensor_set(double* t, strata_int i, strata_float v) { t[i] = v; }
static strata_float strata_tensor_get(double* t, strata_int i) { return t[i]; }

static double strata_activate(double x, char a) {
    if (a == 'r') return x > 0.0 ? x : 0.0;
    if (a == 's') return 1.0 / (1.0 + exp(-x));
    return x;
}

/* Total weights a model needs: for each layer, in*out plus out biases. */
static size_t strata_weight_count(StrataModel* m) {
    size_t n = 0;
    for (int l = 0; l < m->nlayers; l++)
        n += (size_t)m->dims[l] * m->dims[l + 1] + m->dims[l + 1];
    return n;
}

static double* strata_predict(void* model, double* input) {
    StrataModel* m = (StrataModel*)model;
    double* cur = input;
    double* owned = NULL;
    if (!m->weights) {
        /* untrained: zeros, not garbage */
        return (double*)calloc((size_t)m->cols_out, sizeof(double));
    }
    size_t off = 0;
    for (int l = 0; l < m->nlayers; l++) {
        int ci = m->dims[l], co = m->dims[l + 1];
        double* out = (double*)calloc((size_t)co, sizeof(double));
        for (int j = 0; j < co; j++) {
            double acc = m->weights[off + (size_t)ci * co + j];   /* bias */
            for (int i = 0; i < ci; i++)
                acc += cur[i] * m->weights[off + (size_t)i * co + j];
            out[j] = strata_activate(acc, m->acts[l]);
        }
        off += (size_t)ci * co + co;
        if (owned) free(owned);
        owned = out;
        cur = out;
    }
    return cur;
}

/* Weights are plain whitespace-separated numbers, laid out layer by layer:
   for each layer, cols_in*cols_out of them, then cols_out biases. A text
   format keeps the runtime dependency-free and the file inspectable. */
static strata_int strata_model_load(void* model, strata_str path) {
    StrataModel* m = (StrataModel*)model;
    FILE* f = fopen(path, "r");
    if (!f) return 0;
    size_t n = strata_weight_count(m);
    double* w = (double*)calloc(n, sizeof(double));
    size_t got = 0;
    while (got < n && fscanf(f, "%lf", &w[got]) == 1) got++;
    fclose(f);
    if (got < n) {
        fprintf(stderr, "[STRATA MODEL] '%s' holds %zu weights; this model "
                        "needs %zu. Not loading a partial model.\n",
                path, got, n);
        free(w);
        return 0;
    }
    m->weights = w;
    return 1;
}

/* ── Stream context ───────────────────────────────────────────────────────
   The message a `stream` handler is currently processing. There is no
   transport: no broker client, no socket, no scheduler. A host sets this
   before invoking a handler, and it is empty otherwise. Empty is the honest
   default — returning invented traffic would make a handler look like it
   worked when nothing was connected. */
static strata_str __strata_current_message = "";
static strata_str current_message(void) { return __strata_current_message; }
static void strata_set_message(strata_str m) { __strata_current_message = m; }

/* Element-wise tensor addition. Plain scalar loops — the C compiler may
   vectorise them, but Strata emits no SIMD intrinsics of its own. */
static double* strata_tensor_add(double* a, double* b, strata_int n) {
    double* r = (double*)calloc((size_t)n, sizeof(double));
    for (strata_int i = 0; i < n; i++) r[i] = a[i] + b[i];
    return r;
}

/* ── Table persistence ────────────────────────────────────────────────────
   Rows are written as tab-separated text, one per line, with tabs, newlines
   and backslashes escaped in string fields. Text rather than a binary format
   so a table is inspectable with the tools everyone already has, and readable
   by something that is not this compiler.

   There is no schema version, no migration and no locking. A file written by
   one schema and read by another will mis-parse; two writers will corrupt it.
   Suitable for a single process keeping state across restarts. */
static void strata_write_escaped(FILE* f, strata_str s) {
    if (!s) return;
    for (const char* p = s; *p; p++) {
        if (*p == '\\') fputs("\\\\", f);
        else if (*p == '\t') fputs("\\t", f);
        else if (*p == '\n') fputs("\\n", f);
        else fputc(*p, f);
    }
}

/* Reads one escaped field up to a tab or newline. Returns 0 at end of line. */
static int strata_read_field(FILE* f, char* buf, int cap) {
    int n = 0, c;
    while ((c = fgetc(f)) != EOF && c != '\t' && c != '\n') {
        if (c == '\\') {
            int e = fgetc(f);
            if (e == 't') c = '\t';
            else if (e == 'n') c = '\n';
            else if (e == '\\') c = '\\';
            else c = e;
        }
        if (n < cap - 1) buf[n++] = (char)c;
    }
    buf[n] = '\0';
    if (c == EOF && n == 0) return -1;
    return c == '\n' ? 0 : 1;
}
/* ── Schema headers ───────────────────────────────────────────────────────
   A saved table carries a header line naming its columns and their types:

       #strata\tSales\tid:i\tregion:s\tamount:f

   so a file written by one version of a schema can be read by another.
   Columns are matched by name, not by position: one that has since been
   dropped is skipped, one that is new is left at its zero value, and one
   whose type changed is a refusal rather than a silent misread. Without the
   header, adding a column to a `database` block silently corrupted every row
   in every file already on disk. */
#define STRATA_MAX_COLS 64
#define STRATA_NAME_CAP 64

/* Returns the number of columns in the header, -1 if the file has no header
   (written before headers existed), or -2 if the file is empty. */
static int strata_read_header(FILE* f, char names[][STRATA_NAME_CAP],
                              char* types, int cap) {
    char buf[256];
    int n = 0, more;
    more = strata_read_field(f, buf, 256);
    if (more < 0) return -2;
    if (strcmp(buf, "#strata") != 0) return -1;
    if (more == 0) return 0;
    more = strata_read_field(f, buf, 256);          /* table name */
    while (more > 0 && n < cap) {
        more = strata_read_field(f, buf, 256);
        char* colon = strchr(buf, ':');
        if (colon) {
            *colon = '\0';
            strncpy(names[n], buf, STRATA_NAME_CAP - 1);
            names[n][STRATA_NAME_CAP - 1] = '\0';
            types[n] = colon[1];
            n++;
        }
        if (more == 0) break;
    }
    return n;
}

static void strata_load_refuse(const char* table, const char* path,
                               const char* why) {
    fprintf(stderr, "[STRATA LOAD] %s: refusing to read '%s' — %s\n",
            table, path, why);
}

static strata_str strata_dup(const char* s) {
    size_t n = strlen(s); char* r = (char*)malloc(n + 1);
    memcpy(r, s, n + 1); return r;
}

/* ── Test harness ─────────────────────────────────────────────────────────
   A `verify` block compiles to a function; in test mode an entry point runs
   each one and reports. Assertions record a failure rather than terminating,
   so one broken assertion does not hide the rest of the block. */
static int __strata_fail_count = 0;
static int __strata_assert_count = 0;

static void __strata_assert(int cond, const char* expr, int line) {
    __strata_assert_count++;
    if (!cond) {
        __strata_fail_count++;
        fprintf(stderr, "    FAIL  line %d: %s\n", line, expr);
    }
}

/* ── Stream dispatch ──────────────────────────────────────────────────────
   A `stream` block is a handler for a named channel. Messages are queued with
   strata_publish and delivered by strata_run, which drains the queue and
   calls each handler registered for that channel.

   This is a cooperative single-threaded loop, not a fiber scheduler. There
   are no separate stacks, no preemption, no parallelism and no I/O
   integration: a handler runs to completion before the next message is
   delivered, and publishing from inside a handler appends to the same queue.
   It gives `stream` and current_message() real semantics; it does not make
   them concurrent. */
#define STRATA_QUEUE_CAP 4096
#define STRATA_HANDLER_CAP 256

typedef void (*StrataHandler)(strata_str);

static struct { strata_str channel; StrataHandler fn; }
    __strata_handlers[STRATA_HANDLER_CAP];
static int __strata_handler_count = 0;

static struct { strata_str channel; strata_str message; }
    __strata_queue[STRATA_QUEUE_CAP];
static int __strata_q_head = 0, __strata_q_tail = 0;

static void strata_on(strata_str channel, StrataHandler fn) {
    if (__strata_handler_count < STRATA_HANDLER_CAP) {
        __strata_handlers[__strata_handler_count].channel = channel;
        __strata_handlers[__strata_handler_count].fn = fn;
        __strata_handler_count++;
    }
}

static strata_int strata_publish(strata_str channel, strata_str message) {
    int next = (__strata_q_tail + 1) % STRATA_QUEUE_CAP;
    if (next == __strata_q_head) return 0;      /* full: refuse, do not drop silently */
    __strata_queue[__strata_q_tail].channel = channel;
    __strata_queue[__strata_q_tail].message = message;
    __strata_q_tail = next;
    return 1;
}

/* Drains the queue, returning how many messages were delivered. A handler may
   publish; those messages are delivered in the same run. */
static strata_int strata_run(void) {
    strata_int delivered = 0;
    while (__strata_q_head != __strata_q_tail) {
        strata_str ch = __strata_queue[__strata_q_head].channel;
        strata_str msg = __strata_queue[__strata_q_head].message;
        __strata_q_head = (__strata_q_head + 1) % STRATA_QUEUE_CAP;
        for (int i = 0; i < __strata_handler_count; i++) {
            if (strcmp(__strata_handlers[i].channel, ch) == 0) {
                strata_set_message(msg);
                __strata_handlers[i].fn(msg);
                strata_set_message("");
                delivered++;
            }
        }
    }
    return delivered;
}
