
/* Generated by Strata Stage 0 Bootstrap Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include <ctype.h>

typedef int64_t   strata_int;
typedef double    strata_float;
typedef char*     strata_str;
typedef int64_t   strata_bool;

#define STRATA_TRUE  1
#define STRATA_FALSE 0

int __strata_argc = 0;
char** __strata_argv = NULL;

static strata_str strata_concat(strata_str a, strata_str b) {
    size_t la=strlen(a),lb=strlen(b);
    strata_str r=(strata_str)malloc(la+lb+1);
    memcpy(r,a,la); memcpy(r+la,b,lb+1); return r;
}
static strata_str strata_int_to_str(strata_int v) {
    strata_str b=(strata_str)malloc(32);
    snprintf(b,32,"%lld",(long long)v); return b;
}
static strata_str strata_float_to_str(strata_float v) {
    /* %.17g round-trips, then trailing zeros are trimmed so 91.4 prints as
       "91.4" rather than "91.400000". A fixed 6-decimal format made every
       rendered float look padded. */
    strata_str b=(strata_str)malloc(64);
    /* Shortest representation that reads back as the same double: %.17g always
       round-trips but shows binary noise (91.400000000000006), so try shorter
       precisions first. */
    int p;
    for (p = 15; p <= 17; p++) {
        snprintf(b,64,"%.*g",p,v);
        if (strtod(b,NULL) == v) break;
    }
    if (!strchr(b,'e') && !strchr(b,'E')) {
        char* dot=strchr(b,'.');
        if (dot) {
            char* end=b+strlen(b)-1;
            while (end>dot && *end=='0') { *end='\0'; end--; }
            if (end==dot) { *(end+1)='0'; *(end+2)='\0'; }
        } else {
            /* A float is shown as a float: 3.0, not 3. */
            strcat(b,".0");
        }
    }
    return b;
}
static strata_int str_len(strata_str s) { return (strata_int)strlen(s); }
static strata_str str_concat(strata_str a, strata_str b) { return strata_concat(a,b); }
static strata_str int_to_str(strata_int v) { return strata_int_to_str(v); }
static strata_str float_to_str(strata_float v) { return strata_float_to_str(v); }
static strata_int str_eq(strata_str a, strata_str b) { return strcmp(a,b)==0?1:0; }
static strata_int str_to_int(strata_str s) { return (strata_int)atoll(s); }
static strata_str str_slice(strata_str s, strata_int start, strata_int end) {
    strata_int len=(strata_int)strlen(s);
    if(start<0)start=0; if(end>len)end=len;
    strata_int sz=end-start; if(sz<=0)return "";
    strata_str r=(strata_str)malloc(sz+1);
    memcpy(r,s+start,sz); r[sz]='\0'; return r;
}
static strata_int str_index_of(strata_str h, strata_str n) {
    char* p=strstr(h,n); return p?(strata_int)(p-h):-1;
}
static strata_int str_starts_with(strata_str s, strata_str p) {
    return strncmp(s,p,strlen(p))==0?1:0;
}
static strata_str file_read(strata_str path) {
    FILE* f=fopen(path,"r"); if(!f)return "";
    fseek(f,0,SEEK_END); long sz=ftell(f); rewind(f);
    char* b=(char*)malloc(sz+1); fread(b,1,sz,f); b[sz]='\0'; fclose(f); return b;
}
static strata_int file_write(strata_str path, strata_str content) {
    FILE* f=fopen(path,"w"); if(!f)return 0;
    fputs(content,f); fclose(f); return 1;
}
static strata_int file_exists(strata_str path) {
    FILE* f=fopen(path,"r"); if(f){fclose(f);return 1;} return 0;
}

/* StringBuilder */
typedef struct { char* buf; int64_t len; int64_t cap; } SB;
static SB sb_new_f(void) { SB s; s.cap=4096;s.len=0;s.buf=(char*)malloc(4096);s.buf[0]='\0';return s; }
static void sb_append_f(SB* s, const char* t) {
    size_t tl=strlen(t);
    while(s->len+(int64_t)tl+1>s->cap){s->cap*=2;s->buf=(char*)realloc(s->buf,s->cap);}
    memcpy(s->buf+s->len,t,tl+1); s->len+=(int64_t)tl;
}
static void sb_append_line_f(SB* s, const char* t) {
    sb_append_f(s,t); sb_append_f(s,"\n");
}

/* ── In-memory table runtime ──────────────────────────────────────────────
   Each `database` block gets a fixed-capacity table of row pointers. A query
   allocates a NULL-terminated array of matching rows; `len` counts it. This is
   deliberately the simplest thing that makes the cross-tier contract
   observable end to end — there is no persistence, no index and no
   transaction. */
#define STRATA_TABLE_CAP 4096

static strata_int strata_len(void* rows) {
    void** r = (void**)rows;
    strata_int n = 0;
    if (!r) return 0;
    while (r[n]) n++;
    return n;
}
