
/* Generated by Strata — WebAssembly runtime prelude */

/* A freestanding WebAssembly build has no libc: no stdio, no malloc, no
   string.h. This prelude supplies the subset the language needs, so the same
   Strata source can target a browser without pulling in a C runtime.
   Consequences, stated rather than hidden:
     - No file I/O. file_read / file_write / file_exists do not exist here.
     - print writes through an imported host function; a module that never
       calls it imports nothing.
     - Memory is a bump allocator. There is no free; a long-running module
       will exhaust its heap. Suitable for compute, not for a server. */

typedef long long          strata_int;
typedef double             strata_float;
typedef char*              strata_str;
typedef long long          strata_bool;
typedef unsigned long      size_t;
typedef long long          int64_t;
typedef unsigned long long uintptr_t;

#define NULL ((void*)0)
#define STRATA_TABLE_CAP 4096

static int   __strata_argc = 0;
static char** __strata_argv = 0;

/* ── Bump allocator ─────────────────────────────────────────────────────── */
extern unsigned char __heap_base;
static unsigned long __bump = 0;

static void* malloc(size_t n) {
    if (__bump == 0) __bump = (unsigned long)&__heap_base;
    unsigned long p = (__bump + 7UL) & ~7UL;   /* 8-byte aligned */
    __bump = p + n;
    return (void*)p;
}
static void* calloc(size_t n, size_t sz) {
    unsigned long total = (unsigned long)n * (unsigned long)sz;
    unsigned char* p = (unsigned char*)malloc(total);
    for (unsigned long i = 0; i < total; i++) p[i] = 0;
    return p;
}
static void* realloc(void* old, size_t n) {
    unsigned char* p = (unsigned char*)malloc(n);
    unsigned char* o = (unsigned char*)old;
    if (o) for (unsigned long i = 0; i < n; i++) p[i] = o[i];
    return p;
}
static void free(void* p) { (void)p; }

/* ── Minimal string support ─────────────────────────────────────────────── */
static size_t strlen(const char* s) { size_t n=0; while (s[n]) n++; return n; }
static int strcmp(const char* a, const char* b) {
    while (*a && *a == *b) { a++; b++; }
    return (int)((unsigned char)*a) - (int)((unsigned char)*b);
}
static void* memcpy(void* d, const void* s, size_t n) {
    unsigned char* dd=(unsigned char*)d; const unsigned char* ss=(const unsigned char*)s;
    for (size_t i=0;i<n;i++) dd[i]=ss[i];
    return d;
}
static char* strchr(const char* s, int c) {
    while (*s) { if (*s == (char)c) return (char*)s; s++; }
    return NULL;
}
static char* strcat(char* d, const char* s) {
    size_t n = strlen(d); size_t i = 0;
    while (s[i]) { d[n+i] = s[i]; i++; }
    d[n+i] = '\0'; return d;
}

/* ── Host interface ─────────────────────────────────────────────────────── */
/* The host supplies one function. A module that never prints imports nothing. */
__attribute__((import_module("strata"), import_name("print")))
extern void __strata_host_print(const char* s, int len);

static void puts(const char* s) { __strata_host_print(s, (int)strlen(s)); }

/* ── Conversions ────────────────────────────────────────────────────────── */
static strata_str strata_concat(strata_str a, strata_str b) {
    size_t la=strlen(a), lb=strlen(b);
    char* r=(char*)malloc(la+lb+1);
    memcpy(r,a,la); memcpy(r+la,b,lb); r[la+lb]='\0';
    return r;
}
static strata_str strata_int_to_str(strata_int v) {
    char* b=(char*)malloc(24); int i=0; int neg = v<0;
    unsigned long long u = neg ? (unsigned long long)(-v) : (unsigned long long)v;
    char tmp[24]; int n=0;
    if (u==0) tmp[n++]='0';
    while (u) { tmp[n++]=(char)('0'+(u%10)); u/=10; }
    if (neg) b[i++]='-';
    while (n) b[i++]=tmp[--n];
    b[i]='\0'; return b;
}
static strata_str strata_float_to_str(strata_float v) {
    /* Fixed six decimals: the shortest-round-trip loop in the native prelude
       needs snprintf and strtod, which do not exist here. */
    char* b=(char*)malloc(48); int i=0;
    if (v < 0) { b[i++]='-'; v = -v; }
    long long ip=(long long)v;
    strata_str is=strata_int_to_str((strata_int)ip);
    size_t n=strlen(is); memcpy(b+i,is,n); i+=(int)n;
    b[i++]='.';
    strata_float frac = v - (strata_float)ip;
    for (int d=0; d<6; d++) { frac*=10; int dig=(int)frac; b[i++]=(char)('0'+dig); frac-=dig; }
    b[i]='\0'; return b;
}
static strata_int str_len(strata_str s) { return (strata_int)strlen(s); }
static strata_str str_concat(strata_str a, strata_str b) { return strata_concat(a,b); }
static strata_str int_to_str(strata_int v) { return strata_int_to_str(v); }
static strata_str float_to_str(strata_float v) { return strata_float_to_str(v); }
static strata_int str_eq(strata_str a, strata_str b) { return strcmp(a,b)==0?1:0; }
static strata_int str_to_int(strata_str s) {
    strata_int r=0; int neg=0; if (*s=='-'){neg=1;s++;}
    while (*s>='0'&&*s<='9') { r=r*10+(*s-'0'); s++; }
    return neg?-r:r;
}
static strata_str str_slice(strata_str s, strata_int start, strata_int end) {
    strata_int n=(strata_int)strlen(s);
    if (start<0) start=0; if (end>n) end=n; if (end<start) end=start;
    char* r=(char*)malloc((size_t)(end-start+1));
    memcpy(r,s+start,(size_t)(end-start)); r[end-start]='\0';
    return r;
}
static strata_int str_index_of(strata_str h, strata_str n) {
    strata_int hl=(strata_int)strlen(h), nl=(strata_int)strlen(n);
    for (strata_int i=0;i+nl<=hl;i++) {
        strata_int j=0; while (j<nl && h[i+j]==n[j]) j++;
        if (j==nl) return i;
    }
    return -1;
}
static strata_int str_starts_with(strata_str s, strata_str p) {
    return str_index_of(s,p)==0 ? 1 : 0;
}
/* A list carries its element count in the word before its data; see the
   native prelude for why NULL-termination cannot work. */
static void* strata_list_new(strata_int count, size_t elem_size) {
    strata_int* base = (strata_int*)calloc(1, sizeof(strata_int)
                                              + (size_t)count * elem_size);
    if (!base) return NULL;
    base[0] = count;
    return (void*)(base + 1);
}
static void strata_list_set_len(void* list, strata_int count) {
    if (list) ((strata_int*)list)[-1] = count;
}
static strata_int strata_len(void* list) {
    if (!list) return 0;
    return ((strata_int*)list)[-1];
}

/* ── Inference runtime ────────────────────────────────────────────────────
   The same dense layer as the native prelude. Weight loading is absent: a
   freestanding module has no file system, so weights must be written into the
   model by the host through memory. */
#define STRATA_MAX_LAYERS 16

/* A model is a stack of dense layers; see the native prelude for the layout.
   Kept identical here so the same generated instance initialiser is valid for
   both targets. */
typedef struct {
    int rows_in, cols_in, rows_out, cols_out;
    double* weights;
    int nlayers;
    int dims[STRATA_MAX_LAYERS + 1];
    char acts[STRATA_MAX_LAYERS];
} StrataModel;

static double* strata_tensor(strata_int n) {
    return (double*)calloc((size_t)n, sizeof(double));
}
static void strata_tensor_set(double* t, strata_int i, strata_float v) { t[i] = v; }
static strata_float strata_tensor_get(double* t, strata_int i) { return t[i]; }

/* Freestanding WebAssembly has no libm, so exp is written here rather than
   linked. Range reduction x = k*ln2 + r with |r| <= ln2/2, a Taylor series on
   r, then the power of two applied by constructing its exponent bits. */
static double strata_exp(double x) {
    if (x > 709.0)  return 1.0 / 0.0;
    if (x < -745.0) return 0.0;
    const double LN2 = 0.69314718055994530942;
    int k = (int)(x / LN2 + (x < 0 ? -0.5 : 0.5));
    double r = x - k * LN2;
    double term = 1.0, sum = 1.0;
    for (int i = 1; i <= 14; i++) { term *= r / i; sum += term; }
    /* 2^k as a double, built from its exponent field. */
    union { double d; unsigned long long u; } p2;
    int e = k + 1023;
    if (e <= 0)    return 0.0;
    if (e >= 2047) return 1.0 / 0.0;
    p2.u = (unsigned long long)e << 52;
    return sum * p2.d;
}

static double strata_activate(double x, char a) {
    if (a == 'r') return x > 0.0 ? x : 0.0;
    if (a == 's') return 1.0 / (1.0 + strata_exp(-x));
    return x;
}

static double* strata_predict(void* model, double* input) {
    StrataModel* m = (StrataModel*)model;
    double* cur = input;
    if (!m->weights) return (double*)calloc((size_t)m->cols_out, sizeof(double));
    size_t off = 0;
    for (int l = 0; l < m->nlayers; l++) {
        int ci = m->dims[l], co = m->dims[l + 1];
        double* out = (double*)calloc((size_t)co, sizeof(double));
        for (int j = 0; j < co; j++) {
            double acc = m->weights[off + (size_t)ci * co + j];
            for (int i = 0; i < ci; i++)
                acc += cur[i] * m->weights[off + (size_t)i * co + j];
            out[j] = strata_activate(acc, m->acts[l]);
        }
        off += (size_t)ci * co + co;
        cur = out;
    }
    return cur;
}

/* Element-wise tensor addition. Plain scalar loops — the C compiler may
   vectorise them, but Strata emits no SIMD intrinsics of its own. */
static double* strata_tensor_add(double* a, double* b, strata_int n) {
    double* r = (double*)calloc((size_t)n, sizeof(double));
    for (strata_int i = 0; i < n; i++) r[i] = a[i] + b[i];
    return r;
}
